on:
  push:
    branches:
      - master
    pull_request:
      - master

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.4

      - name: maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: test
        run: lein midje

      - name: ls
        run: ls -al

      - name: timestamp
        # by setting INFERV_TIMESTAMP_MS we will get deterministic versions from
        # `lein pprint :version`
        run: echo "INFERV_TIMESTAMP_MS=`date +%s%3N`" >> $GITHUB_ENV

      - name: env
        run: env

      - name: release
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: lein with-profile deploy release
