on:
  push:
    branches:
      - master
    pull_request:
      - master

jobs:

  release:
    runs-on: ubuntu-latest
    container: clojure:lein
    steps:
      # lein  image doesn't come with git anymore. make sure to install git
      # before actions/checkout or actions/checkout will use the REST API and
      # there won't be a .git folder present, which lein expects during release.
      - name: install-git
        run: apt update && apt install -y git
      - name: checkout
        uses: actions/checkout@v3
      - name: test
        run: lein midje
      - name: ls
        run: ls -al
      - name: release
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: lein with-profile deploy release
