on:
  push:
    branches:
      - master
    pull_request:
      - master

jobs:

  release:
    runs-on: ubuntu-latest
    container: clojure:lein
    steps:
      - name: checkout
        uses: actions/checkout@v3
      # lein  image doesn't come with git anymore
      - name: install-git
        run: apt update && apt install -y git
      - name: test
        run: lein midje
      - name: release
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: lein with-profile deploy release
